source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ColorPicker_Example', :exclusive => true do
  pod 'ColorPicker', :path => '../'
end

target 'ColorPicker_Tests', :exclusive => true do
  pod 'ColorPicker', :path => '../'

  
end
